name: Reset Free Users Usage

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号凌晨执行

jobs:
  reset-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Reset Free Users Usage
        run: |
          curl -X POST \
          https://<your-project>.supabase.co/functions/v1/reset-free-users \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" 